import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/global/navbar";
import { AuthContext } from "@/provider/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <main className="flex h-screen w-screen flex-col space-y-[2vh] items-center bg-[#bdbdbd]">
            <Navbar />
            {children}
          </main>
        </AuthContext>
      </body>
    </html>
  );
}
